Feature/2 검색 페이지 제작 2
team-ecolink/ecolink-frontend pull request #34
Opened 2024-01-24 14:11 UTC by warmzer0

### Issue Title: 
#### Issue Page Name: 
* 추가/수정 기능: 
설명: 

#### To Reviewers
:

2024-01-24 14:33 UTC, PROMLEE requested changes
전체적으로 잘하셨네요 👍 
리뷰 확인하시고 **해당 브랜치 pull 해가신 후**에 수정 후 다시 push 부탁드려요!

2024-01-24 14:33 UTC, PROMLEE commented on src/components/SearchFile/SearchResultList.tsx
> +
상단 margin 확인해주세요!

2024-01-24 14:33 UTC, PROMLEE commented on src/components/SearchFile/NoSearchFile.tsx
> +    margin: 482px 900px 16px 900px;
상단 margin 확인해주세요!

2024-01-24 14:33 UTC, PROMLEE commented on src/components/SearchFile/SearchResultList.tsx
> +  font-family: 'Noto Sans';
저희 글꼴명은 'Noto Sans KR' 입니다!
다른 style도 수정해주세요!

2024-01-24 14:33 UTC, PROMLEE commented on src/components/SearchFile/NoSearchFile.tsx
> + wordWrap: 'break-word'
각 요소 이름은
font-size
font-family
font-weight
word-wrap
입니다!

2024-01-24 14:33 UTC, PROMLEE commented on src/components/SearchFile/SearchResultList.tsx
> +  width: 924px;
다음 작업부터는 기본적으로 em 단위 사용 부탁드려요!(필요시 px 혼용 가능)

2024-01-25 00:25 UTC, warmzer0 commented on src/components/SearchFile/SearchResultList.tsx
> +
말씀하신 부분 모두 수정해서 브랜치에 다시 push했습니다 !!
명세서에서 구현이 안된 부분은 이슈에 올려두겠습니다 !
수정사항 있으면 말씀 부탁드려요 :)

2024-01-25 04:49 UTC, PROMLEE approved these changes
수고하셨습니다!

2024-01-25 15:07 UTC, merged