Feature/33 계정관리 페이지 제작
team-ecolink/ecolink-frontend pull request #41
Opened 2024-01-31 12:20 UTC by rlotr02

### Issue Title: Feature/33 계정관리 페이지 제작
#### Issue Page Name: AccountSetting
* 추가/수정 기능: 계정관리 페이지 제작, 로그아웃/회원탈퇴 모달창 제작, 폰트 수정
설명: 

#### To Reviewers
: /accountsetting

2024-02-01 17:54 UTC, PROMLEE approved these changes
고생하셨습니다~ 사진 크롭 부분이 많이 어려울 것이라 걱정했는데 잘하셨네요 👍 
#40 닉네임 설정 페이지 제작 PR보다 이게 커밋 하나 더 들어와 있어 이 PR 하나만 병합하도록 하겠습니다
리뷰 확인해 주세요!

2024-02-01 17:54 UTC, PROMLEE commented on src/components/Edit/ProfileImgModal.tsx
현재 모바일에서는 확대축소가 작동하지 않는데 기술적으로 힘든 것일까요 ❓ 
모바일에는 스크롤 이벤트가 없어서 그런 것 같네요

2024-02-01 17:54 UTC, PROMLEE commented on src/pages/AccountSetting.tsx
모달 내부에 스크롤 이벤트가 있기 때문에 모달이 켜져 있을 때 이 페이지 스크롤은 잠가두는 게 좋겠네요!
`document.body.style.overflow =  {모달 상태} ? 'hidden' : 'unset';`
프로필 이미지 설정 모달에 대한 상태를 적용해 이 페이지에 추가하면 될 것 같네요 😄

2024-02-01 17:54 UTC, PROMLEE commented on src/pages/AccountSetting.tsx
> +import AccountModal from '../components/Edit/AccountModal';
이렇게 나열하기 불편하시면 Edit 폴더 내에도 index.ts 파일 만들어서 사용하셔도 됩니다! (선택사항)

2024-02-02 04:36 UTC, PROMLEE requested changes
수정 부탁드립니다

2024-02-02 04:36 UTC, PROMLEE commented on src/App.tsx
> +          <Route path="/accountsetting" element={<AccountSetting />} />
라우팅은 위에 있는 setting 쓰시면 될 것 같네요!

2024-02-04 09:23 UTC, rlotr02 commented on src/components/Edit/ProfileImgModal.tsx
제가 사용한 라이브러리에 확대/축소 기능이 없어서 그런거였는데 만들어서 추가해뒀습니다

2024-02-04 09:23 UTC, rlotr02 commented on src/pages/AccountSetting.tsx
모달창 켜져있을 때 페이지 스크롤 안되도록 수정 완료했습니다

2024-02-04 09:24 UTC, rlotr02 commented on src/App.tsx
> +          <Route path="/accountsetting" element={<AccountSetting />} />
수정 완료했습니다!

2024-02-04 10:56 UTC, PROMLEE approved these changes

2024-02-04 15:14 UTC, merged