Feature/39 매장 상세 페이지 팝업 제작
team-ecolink/ecolink-frontend pull request #42
Opened 2024-01-31 17:28 UTC by warmzer0

### Issue Title: 매장 상세 페이지 팝업 제작
#### Issue Page Name: 
* 추가/수정 기능: 
설명: 공유하기 팝업창에 링크 연결은 따로 안했습니다

#### To Reviewers
:

2024-02-01 17:17 UTC, PROMLEE requested changes
고생하셨습니다 👍 전체적으로 잘하셨네요!
리뷰가 좀 많아졌는데 최우선으로 처리해야 할 점은 **모달을 열고 닫는 상태 관리** 쪽 문제입니다
관련사항 고치기 전 `src/pages/StoreDetail.tsx`의 8,18번째 줄, `src/recoil/reviewwritemodal.ts`의 3~6번째 모달 관련 상태를 한번 참고해 보세요!
모든 모달은 각각 하나씩의 전역 상태(atom)가 필요합니다
개발하시다가 모르거나 궁금한 점은 언제든지 저와 팀원들에게 물어보세요 😄

2024-02-01 17:17 UTC, PROMLEE commented on src/components/DetailPopup/DetailPopup.tsx
Quiz: 왜 이 모달을 열면 항상 커서가 pointer 형식일까요 ❓

2024-02-04 11:51 UTC, warmzer0 commented on src/components/DetailPopup/DetailPopup.tsx
제가 스타일 컴포넌트 설정을 잘못준것 같네요 ! 고쳤습니다 !

2024-02-04 15:38 UTC, PROMLEE commented
모달창 통일성을 위해 마무리작업 했습니다!

2024-02-04 15:39 UTC, PROMLEE approved these changes

2024-02-04 15:39 UTC, merged