Feature/37 홈화면 페이지 제작
team-ecolink/ecolink-frontend pull request #43
Opened 2024-01-31 18:17 UTC by jihye9549

### Issue Title: 홈화면 퍼블리싱
#### Issue Page Name: 37
* 추가/수정 기능: 
설명: 홈화면 슬라이더 / 마우스 스크롤 구현 /홈 탭 구현

#### To Reviewers
:

2024-02-01 15:59 UTC, PROMLEE requested changes
슬라이드 화면 구현과 마우스 드래그 구현 등 어려운 화면인데 완성도 높게 잘하셨네요 👍 
리뷰 확인 해주세요!

2024-02-01 15:59 UTC, PROMLEE commented on src/components/Home/Contents/StoreInfo.tsx
> +  );
피그마 보시면 매장 정보 아래에 미세하게 구분선이 보이네요
`Info` 태그에 border-bottom 스타일 추가해 주시면 될 거 같아요!

2024-02-01 15:59 UTC, PROMLEE commented on src/components/Home/Contents/Items.tsx
> +            <p>{item.storeName}</p>
매장명을 나타내는 텍스트에 fontsize가 적용 안되어있는 것 같네요 1.4 rem입니다!

2024-02-01 15:59 UTC, PROMLEE commented on src/components/Home/Contents/StoreInfo.tsx
> +          <Count>{`(${info.reviewCount})`}</Count>
왼쪽에 있는 별 모양과 위치를 봤을 때 디자인상으로는 별의 중앙에 글씨가 맞춰져 있는 것 같아 보이네요
지금은 별의 하단에 맞춰져 지도록 구성하신 것 같은데 `Score`과 `Count`태그의 상단 margin을 없애는 게 어떨까요?

2024-02-02 06:52 UTC, jihye9549 commented on src/components/Home/Contents/StoreInfo.tsx
> +  );
왓 너무 미세해서 못봤어요!! 수정했습니당

2024-02-02 06:56 UTC, jihye9549 commented on src/components/Home/Contents/StoreInfo.tsx
> +          <Count>{`(${info.reviewCount})`}</Count>
margin을 다 빼면 너무 위로올라가서  0.5rem -> 0.2rem으로 수정했습니다 !!

2024-02-02 08:31 UTC, PROMLEE approved these changes

2024-02-04 15:13 UTC, merged